language: c

dist: trusty

branches:
  only:
  - master

compiler:
- gcc

install:
- sudo apt-get -qq update
- sudo apt-get install build-essential
- sudo apt-get install libgtk-3-dev

script:
- make

after_success:
- bash deploy.sh

deploy:
  provider: releases
  api_key:
    secure: Ssu8d38M8umf3UVDCNdX3a/YCskbgX3x4Bp8CQ8TbTmuyAc+XIGG8wVKJKWTJoFqHmbQppvAsW6uGtW+ayZmrtAO3ZDbSoVxhIZtVttvBT7TwWdE+sF9sRRjpQRpUy3iX704p7FrMobVUym+rPDmvm1pB2ikQix2BA3HJSxs73N+n5tUWpc4Uv2sUJgz2M04t1N/B68z6ztPF5P4MvgFgp7iqjpjH4gm8eaNePvcFet4y+ActJ0+UNRsWivgdfjvyHn+ynzUkK9cIEFoy7K7vL79QIOPZ58wS9hK4wkG1D4jeRmHpKsUk511NT7WVVq18VrTv9Ut7YKo12dYDaNbyoceBpVV3mo+hGysHKActX6sxN0lnaAEtR7jJ8TM2V7XZj5pcSu84VtMDDA0Ljj2R69D71//hJcVnc5xn2IH/qm3bLr1oAh0rYEkRaTSDb+ilXvyD3yATnkrwYUsuVs8EPEb6vPMx5zXMVELc9oBVhmpy9924eH0JybjkNBnLh2qdg0gIYTvOZL/iEEM8/GX7EWAdTXi5NvBd3T3IXc4pwOOf0rCHOgwnSagQfBxY9KquEAXPJb17wG55afUJbUe4/aux0/TwTkEx/iX4KQ7sibkt2K6vvqG7sdIYElGUCLo7z1R8ScrWiE3TZHUmhAg5/Rl1BBVXixTKrpwjZuwxBs=
  file_glob: true
  skip_cleanup: true
  file:
  - "*.tar.gz"
  on:
    branch: master
    tags: false

env:
  global:
    secure: dcHjlw2gs0/raBx9wrGxiScf4i3QXIwMHRNtfI2dGzCjrSzUkLARjqgjd9LIP+O+nBX0sRH9y+yRlQLj27wKhVnWKAf34Rhh0Z7wyNQcIDMkx87hyz4CjY75KElQxbGo9eM0efMHdgRmDdrrDLTt6wwwXyoyCGGjCWFu5b4V8KJy8sGhE2xygbgQIv1ra5ZGryDnaC7Vq5ecMa+1GvHoVibZFRk1dCH9LO6xwu9myy2J8KRBJJzmHslpfz7WyIxqmH+BDnJ8bJmtHh8x1dQ02fjf64RfQYRNnV0tHodEeopv0w8F0TbGp5ToL96DqhKiR/NdOaKdYZlLUJFluIkIQJJ7RmXnxFa122sY8618LILGlDzBsxkM3BWZ1iVRrtpsQXtBL3S+SRSFNrokIe6onEB3YoecT2SVRn1Xc3gce4Iea2SrosUwlFMvrd6+P+Cu+S5dpoqimWRdB0hXM3r6O3i1LhSY00+A7ktAq2Aq9EzUuIIhjW7/iaMy39m3GbCjXJSqNUte95sCMPG+owv0tBfau0taLmppGclNZzM5N6eh4NshPsFgynD1qbTMstqrpne4zL7ekEZMQ4icjr464oVFFGYlM2iCtNCmuaEYJPK2+pnOH7QBK1WVRtkUll0t+qmIrqg+45TDH1e2M1OY1oAlGev0qEPVFkgflUNYt8E=
